BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/Employee/Controllers/UpcomingMeetingForEmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileAppAndroid.Models;
using MobileAppAndroid.Providers;

namespace MobileAppAndroid.Areas.Employee.Controllers
{
    [Authorize]
    public class UpcomingMeetingForEmployeeController : Controller
    {
        //
        // GET: /Employee/UpcomingMeetingForEmployee/

        public ActionResult Index()
        {
            EmployeeDetailsModel model = new EmployeeDetailsModel();
            MeetingDetailsProviders pro = new MeetingDetailsProviders();
            int EmployeeId = Utilities.GetEmployeeIdFromUserId();
            int OrganizationId = Utilities.GetCurrentEmployeeOrganizationId(EmployeeId);
            DateTime TodayDate = DateTime.Today;

            model.EmployeeMeetingDetailViewModelList = pro.GetEmployeeMeetingDetails(OrganizationId, EmployeeId).Where(x => x.MeetingDate >= TodayDate).ToList();
            return View(model);
        }

        public ActionResult ViewMeetingDetails(int id)
        {
            EmployeeDetailsModel model = new EmployeeDetailsModel();
            MeetingDetailsProviders pro = new MeetingDetailsProviders();
            int EmployeeId = Utilities.GetEmployeeIdFromUserId();
            int OrganizationId = Utilities.GetCurrentEmployeeOrganizationId(EmployeeId);
            DateTime TodayDate = DateTime.Today;

            model.ObjEmployeeMeetingDetailViewModel = pro.GetEmployeeMeetingDetails(OrganizationId, EmployeeId).Where(x=>x.MeetiingDetailsId == id).SingleOrDefault();
            //model.ObjEmployeeMeetingDetailViewModel
            return View(model);
        }

        public ActionResult ListMeeting()
        {
            EmployeeDetailsModel model = new EmployeeDetailsModel();
            MeetingDetailsProviders pro = new MeetingDetailsProviders();
            int EmployeeId = Utilities.GetEmployeeIdFromUserId();
            int OrganizationId = Utilities.GetCurrentEmployeeOrganizationId(EmployeeId);
            model.EmployeeMeetingDetailViewModelList = pro.GetEmployeeMeetingDetails(OrganizationId, EmployeeId).ToList();
            return View(model);
        }
        public ActionResult PostFeedback(int id, int id2)
        {
            return View();
        }

        public ActionResult PostRemarks(int id, int id2)
        {
            return View();
        }


    }
}

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/Employee/Views/UpcomingMeetingForEmployee/Index.cshtml
@model MobileAppAndroid.Models.EmployeeDetailsModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Employee/Views/Shared/_Layout.cshtml";
    int i = 1;
}

<script src="~/Scripts/toastr.min.js"></script>
<link href="~/Content/toastr.min.css" rel="stylesheet" />



<div id="dialog-confirm" style="display: none">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        Are you sure to delete?
    </p>
</div>

<div id="dialog-edit" style="display: none">
</div>
<div id="dialog-detail" style="display: none">
</div>


<div class="padding-md">
    <div class="panel panel-default table-responsive">
        <div class="panel-heading">
            Meeting Details
					
            <span class="label label-info pull-right">1 Items</span>
        </div>
        <div class="padding-md clearfix">
            <table class="table table-striped" id="dataTable">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Meeting Title</th>
                        <th>Agenda</th>
                        <th>Venue</th>
                        <th>Meeting Date</th>


                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.EmployeeMeetingDetailViewModelList.Any())
                    {
                        foreach (var item in Model.EmployeeMeetingDetailViewModelList)
                        {
                        <tr>
                            <td>@i</td>
                            <td>@item.MeetingTitle</td>
                            <td>@item.Agenda</td>
                            <td>@item.Venue</td>
                            <td>@item.MeetingDate.ToShortDateString()</td>

                            <td>
                                <a title="Edit" class="fa fa-edit fa-lg" href="@Url.Action("ViewMeetingDetails", "UpcomingMeetingForEmployee", new { id = item.MeetiingDetailsId })">Edit</a>
                                @*  <a title="Edit" class="fa fa-edit fa-lg" href="@Url.Action("Edit", "UpcomingMeetingForEmployee", new { id = item.MeetiingDetailsId })">Edit</a> ||
                                 <a title="Delete" class="fa fa-minus-circle fa-lg" href="@Url.Action("Delete", "UpcomingMeetingForEmployee", new { id = item.MeetiingDetailsId })" onclick="return confirm('Are you sure you wish to delete?');">Delete</a>*@


                            </td>
                        </tr>
                            i++;
                        }
                    }

                </tbody>
            </table>
        </div>
        <!-- /.padding-md -->
    </div>
    <!-- /panel -->
</div>
<!-- /.padding-md -->

<script>
    $(document).ready(function () {
        var success = @((TempData["SuccessMessage"] != null).ToString().ToLower());
        if (success == true) 
        {

            displayToastr();
        }

    });

    function displayToastr() {
        //alert('yes');
        // Display a info toast, with no title
        toastr.options = {

            "positionClass": "toast-top-center"
        }

        //toastr.options = {
        //    "closeButton": false,
        //    "debug": false,
        //    "newestOnTop": false,
        //    "progressBar": false,
        //    "positionClass": "toast-top-center",
        //    "preventDuplicates": false,
        //    "onclick": null,
        //    "showDuration": "300",
        //    "hideDuration": "1000",
        //    "timeOut": "5000",
        //    "extendedTimeOut": "1000",
        //    "showEasing": "swing",
        //    "hideEasing": "linear",
        //    "showMethod": "fadeIn",
        //    "hideMethod": "fadeOut"
        //}

        toastr.info('Department save successfully.')

        //// Display a warning toast, with no title
        //toastr.warning('Softech Foundation, This the first warning for you!')

        //// Display a success toast, with a title
        //toastr.success('Softech Foudnation!', 'Congratulation for you, Mahedee!')

        //// Display an error toast, with a title
        //toastr.error('Softech Foundation', 'Please contact with system administrator.')
    };
</script>

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/Employee/Views/UpcomingMeetingForEmployee/ListMeeting.cshtml
@model MobileAppAndroid.Models.EmployeeDetailsModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Employee/Views/Shared/_Layout.cshtml";
    int i = 1;
}

<script src="~/Scripts/toastr.min.js"></script>
<link href="~/Content/toastr.min.css" rel="stylesheet" />



<div id="dialog-confirm" style="display: none">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        Are you sure to delete?
    </p>
</div>

<div id="dialog-edit" style="display: none">
</div>
<div id="dialog-detail" style="display: none">
</div>


<div class="padding-md">
    <div class="panel panel-default table-responsive">
        <div class="panel-heading">
           Meeting Details
					
            <span class="label label-info pull-right">1 Items</span>
        </div>
        <div class="padding-md clearfix">
            <table class="table table-striped" id="dataTable">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Meeting Title</th>
                        <th>Agenda</th>
                        <th>Venue</th>
                        <th>Meeting Date</th>


                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.EmployeeMeetingDetailViewModelList.Any())
                    {
                        foreach (var item in Model.EmployeeMeetingDetailViewModelList)
                        {
                        <tr>
                            <td>@i</td>
                            <td>@item.MeetingTitle</td>
                            <td>@item.Agenda</td>
                            <td>@item.Venue</td>
                            <td>@item.MeetingDate.ToShortDateString()</td>

                            <td>

                              @*  <a title="Edit" class="fa fa-edit fa-lg" href="@Url.Action("Edit", "UpcomingMeetingForEmployee", new { id = item.MeetiingDetailsId })">Edit</a> ||
                                 <a title="Delete" class="fa fa-minus-circle fa-lg" href="@Url.Action("Delete", "UpcomingMeetingForEmployee", new { id = item.MeetiingDetailsId })" onclick="return confirm('Are you sure you wish to delete?');">Delete</a>*@


                            </td>
                        </tr>
                            i++;
                        }
                    }

                </tbody>
            </table>
        </div>
        <!-- /.padding-md -->
    </div>
    <!-- /panel -->
</div>
<!-- /.padding-md -->

<script>
    $(document).ready(function () {
        var success = @((TempData["SuccessMessage"] != null).ToString().ToLower());
        if (success == true) 
        {

            displayToastr();
        }

    });

    function displayToastr() {
        //alert('yes');
        // Display a info toast, with no title
        toastr.options = {

            "positionClass": "toast-top-center"
        }

        //toastr.options = {
        //    "closeButton": false,
        //    "debug": false,
        //    "newestOnTop": false,
        //    "progressBar": false,
        //    "positionClass": "toast-top-center",
        //    "preventDuplicates": false,
        //    "onclick": null,
        //    "showDuration": "300",
        //    "hideDuration": "1000",
        //    "timeOut": "5000",
        //    "extendedTimeOut": "1000",
        //    "showEasing": "swing",
        //    "hideEasing": "linear",
        //    "showMethod": "fadeIn",
        //    "hideMethod": "fadeOut"
        //}

        toastr.info('Department save successfully.')

        //// Display a warning toast, with no title
        //toastr.warning('Softech Foundation, This the first warning for you!')

        //// Display a success toast, with a title
        //toastr.success('Softech Foudnation!', 'Congratulation for you, Mahedee!')

        //// Display an error toast, with a title
        //toastr.error('Softech Foundation', 'Please contact with system administrator.')
    };
</script>

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/Employee/Views/UpcomingMeetingForEmployee/ViewMeetingDetails.cshtml
@model MobileAppAndroid.Models.EmployeeDetailsModel

@{
    ViewBag.Title = "ViewMeetingDetails";
    Layout = "~/Areas/Employee/Views/Shared/_Layout.cshtml";
}
<div class="padding-md">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Meeting Details</div>
            <div class="panel-body">
                <div class="form-group col-md-6">
                    <label for="exampleInputEmail1">Meeting Title</label>
                    @Html.TextBoxFor(model => model.ObjEmployeeMeetingDetailViewModel.MeetingTitle, new { @class = "form-control input-sm", @readonly = "readonly" })


                </div>

                <div class="form-group col-md-6">
                    <label for="exampleInputEmail1">Meeting Agenda</label>
                    @Html.TextBoxFor(model => model.ObjEmployeeMeetingDetailViewModel.Agenda, new { @class = "form-control input-sm", @readonly = "readonly" })


                </div>

                <div class="form-group col-md-6">
                    <label for="exampleInputEmail1">Meeting Venue</label>

                    @Html.TextBoxFor(model => model.ObjEmployeeMeetingDetailViewModel.Venue, new { @class = "form-control input-sm", @readonly = "readonly" })

                </div>

                <div class="form-group col-md-3">
                    <label for="exampleInputEmail1">Meeting Date</label>
                    @Html.TextBoxFor(model => model.ObjEmployeeMeetingDetailViewModel.MeetingDate, new { @class = "datepicker form-control", @readonly = "readonly" })

                </div>

                <div class="form-group col-md-3">
                    <label for="exampleInputEmail1">Meeting Time</label>
                    @Html.TextBoxFor(model => model.ObjEmployeeMeetingDetailViewModel.MeetingTime, new { @class = "form-control", @readonly = "readonly" })


                </div>
                <div class="clearfix"></div>

                <div class="form-group col-md-6">
                    <label for="exampleInputEmail1">Attend Status</label>
                    @Html.DropDownList("AttendStaus", MobileAppAndroid.Utilities.MeetingAttendStatus(), new { @class = "form-control input-sm", @required = "required" })


                </div>




                <div class="divider"></div>
                <div class="clearfix"></div>

                <div class="text-right">
                    <input class="btn btn-success btn-sm" type="button" value="Save" onclick="SendStatus()" />
                    @Html.ActionLink("Back", "Index", "AddNewMeeting", null, new { @class = "btn btn-warning btn-sm" })
                    @* <a class="btn btn-warning btn-sm"><i class="fa fa-chevron-left"></i>Back</a>*@
                </div>



            </div>
        </div>

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    function SendStatus() {
        var SendStatus = $("#AttendStaus").val();
        alert(SendStatus);
    };
</script>