BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Controllers/AddNewMeetingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileAppAndroid.Models;
using MobileAppAndroid.Providers;
using System.Net;
using System.Text;
using System.IO;
using System.Web.Script.Serialization;


namespace MobileAppAndroid.Areas.AdminNew.Controllers
{
    public class AddNewMeetingController : Controller
    {
        //
        // GET: /Admin/AddNewMeeting/
        MeetingDetailsProviders pro = new MeetingDetailsProviders();
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Index()
        {
            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            model.MeetingDetailsMainModelList = pro.GetMeetingList();
            return View(model);
        }
        public ActionResult SendNotificationOld()
        {
            //AndroidGCMPushNotification mm = new AndroidGCMPushNotification();
            string ssapk = "AAAAmj_63s8:APA91bFLo3dHQwbrI_KNtRjvFr34__Mu8iByqYPuz-Edzc12cFWUzeH_xauk9wiDDPsYeJcHnmkLTdZys8ymPm9R_-EEl7sa-KepFqfUsEHj6jp3TE8rDMY4rMmDEczcfvNm8am86rOyQX-bWixXv_VLn4VXNjWEQw";
            var ssid = "662498369231";
            string deviceIdcc = "dm_g7DQrAjU:APA91bF6Jx8I4tJFYuO2DLTn30OByM8nh_RzkNvErgPRYfmOvUkZz-oEg-oldZW2ZT5HMETEFr_xUbIhmPI7fo-Kc7V6IjzNAFLaT2wDvwCQ9p3Wwr06GgLjhlqtiEnSlbalyuv1a3ju";
            string messagecc = "testing from code";

            //SendNotificationControllerMM(ssapk, ssid, deviceIdcc, messagecc);

            //mm.SendNotification("dm_g7DQrAjU:APA91bF6Jx8I4tJFYuO2DLTn30OByM8nh_RzkNvErgPRYfmOvUkZz-oEg-oldZW2ZT5HMETEFr_xUbIhmPI7fo-Kc7V6IjzNAFLaT2wDvwCQ9p3Wwr06GgLjhlqtiEnSlbalyuv1a3ju", "Hello Welcome");
            return View();
        }

        public ActionResult AssingEmployee(int id)
        {
            EmployeeDetailsModel model = new EmployeeDetailsModel();
            model.ObjEmployeeMeetingDetailViewModel.MeetiingDetailsId = id;
            EmployeeRecordsProviders empPro=new EmployeeRecordsProviders();
            //Check is Already Assgin Or Not
            model.EmployeeCheckListVMList = empPro.EmployeeCheckList(1);
            if (pro.CheckIsAlreadyEmployeeAssignOrNot(id) > 0)
            {
                model.EmployeeCheckListVMList = empPro.EmployeeCheckListIfExist(id);
            }
           
           

            return View(model);
        
        }

        [HttpPost]
        public ActionResult AssingEmployee(EmployeeDetailsModel model)
        {
            EmployeeRecordsProviders proEmp = new EmployeeRecordsProviders();
            if (proEmp.AssignEmployeeInMeetingFromAdmin(model))
            {
                TempData["SuccessMessage"] = "Meeting Created Successfully";
            }
            else
            {
                TempData["SuccessMessage"] = "Failure";
            }
            return RedirectToAction("Index");
        }

        public ActionResult ViewAssignEmployee(int id)
        {
            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            model.MeetingEmployeeDetailsForAdminVMList = pro.GetMeetingDetailsforAdmin(id).ToList();
            return View(model);
        }
        

        public ActionResult Create()
        {
            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(MeetingDetailsMainModel model)
        {
            string MeetingTimeStr = model.MeetiingDetailsIdStr;

            model.MeetingTime = TimeSpan.Parse(model.MeetiingDetailsIdStr);
            model.MeetingDate = DateTime.Parse(model.ObjReturnMeetingDetailsAdminViewModel.MeetingDate);
            model.CreatedBy = 1;
            model.OrganizationId = 1;
            if (pro.InsertMeetingDetailsAdmin(model))
            {
                TempData["SuccessMessage"] = "Meeting Created Successfully";
            }
            else
            {
                TempData["SuccessMessage"] = "Failure";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            model = pro.GetMeetingList().Where(x => x.MeetiingDetailsId == id).SingleOrDefault();
            return View(model);
        }

        public ActionResult DeleteMeeting(int id)
        {
            MeetingEmployeeDetailsViewModel model = new MeetingEmployeeDetailsViewModel();
            model.MeetingId = id;
            if (pro.DeleteMeetingDetails(model))
            {
                TempData["SuccessMessage"] = "Meeting Deleted Successfully";
            }
            else
            {
                TempData["SuccessMessage"] = "Error Please Try Again";
            }
            return RedirectToAction("Index");
        }







    }
}

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/AddNewMeeting/AssingEmployee.cshtml
@model MobileAppAndroid.Models.EmployeeDetailsModel

@{
    ViewBag.Title = "AssingEmployee";
    Layout = "~/Areas/AdminNew/Views/Shared/_Layout.cshtml";
}



<div class="padding-md">
    <div class="panel panel-default table-responsive">
        <div class="padding-md clearfix">
            @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = " " }))
            {
                @Html.HiddenFor(m=>m.ObjEmployeeMeetingDetailViewModel.MeetiingDetailsId)
                @Html.ValidationSummary(true)


                for (int i = 0; i < Model.EmployeeCheckListVMList.Count; i++)
                {             
                                                  
                                                  
                <span style="margin-right: 3px; margin-bottom: 5px; display: inline-block; background: #F5F5F5; padding: 1px 5px; border: 1px solid #ddd; width: 250px;">
                    @Html.CheckBoxFor(model => Model.EmployeeCheckListVMList[i].IsChecked, new { @class = "custom-checkbox", name = "chk-demo" })&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.HiddenFor(model => Model.EmployeeCheckListVMList[i].EmployeeId)
                    @Html.DisplayFor(model => Model.EmployeeCheckListVMList[i].EmployeeName)
                </span>
                }
                <div class="divider"></div>
                <div class="clearfix"></div>
                <div class="text-right">
                    <input class="btn btn-success btn-sm" type="submit" value="Save" />
                    @Html.ActionLink("Back", "Index", "AddNewMeeting", null, new { @class = "btn btn-warning btn-sm" })
                    @*<a class="btn btn-warning btn-sm"><i class="fa fa-chevron-left"></i>Back</a>*@
                </div>

            }


        </div>
    </div>
</div>

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/AddNewMeeting/Create.cshtml
@model MobileAppAndroid.Models.MeetingDetailsMainModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminNew/Views/Shared/_Layout.cshtml";
}
<link href="~/css/datepicker.css" rel="stylesheet" />
<link href="~/css/bootstrap-timepicker.css" rel="stylesheet" />

<div class="padding-md">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Create New Meeting</div>
            <div class="panel-body">
                @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = " " }))
                {
                    @Html.ValidationSummary(true)
                    @Html.Partial("VUC_Add");
                    <div class="divider"></div>
                    <div class="clearfix"></div>
                        
                    <div class="text-right">
                        <input class="btn btn-success btn-sm" type="submit" value="Save" />
                        @Html.ActionLink("Back", "Index", "AddNewMeeting", null, new { @class = "btn btn-warning btn-sm" })
                        @* <a class="btn btn-warning btn-sm"><i class="fa fa-chevron-left"></i>Back</a>*@
                    </div>
            
   
                }
            </div>
        </div>

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/AddNewMeeting/Edit.cshtml
@model MobileAppAndroid.Models.MeetingDetailsMainModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminNew/Views/Shared/_Layout.cshtml";
}

<link href="~/css/datepicker.css" rel="stylesheet" />
<link href="~/css/bootstrap-timepicker.css" rel="stylesheet" />

<div class="padding-md">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Edit Meeting Description</div>
            <div class="panel-body">
                @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = " " }))
                {
                    @Html.HiddenFor(m => m.MeetiingDetailsId)
                    @Html.ValidationSummary(true)
                    @Html.Partial("VUC_Add");
                    <div class="divider"></div>
                        
                    <div class="text-right">
                        <input class="btn btn-success btn-sm" type="submit" value="Edit" />
                        @Html.ActionLink("Back", "Index", "AddNewMeeting", null, new { @class = "btn btn-warning btn-sm" })
                    </div>
            
   
                }
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/AddNewMeeting/Index.cshtml
@model MobileAppAndroid.Models.MeetingDetailsMainModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminNew/Views/Shared/_Layout.cshtml"; int i = 1;
}


<script src="~/Scripts/toastr.min.js"></script>
<link href="~/Content/toastr.min.css" rel="stylesheet" />

<div id="dialog-alert" style="display: none">
    <p>
        @TempData["msg"]!
    </p>
</div>

<div id="dialog-confirm" style="display: none">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        Are you sure to delete?
    </p>
</div>

<div id="dialog-edit" style="display: none">
</div>
<div id="dialog-detail" style="display: none">
</div>


<div class="padding-md">
    <div class="divider text-right">
        @Html.ActionLink("Add New", "Create", null, new { @class = "btn btn-primary" })
    </div>


    <div class="panel panel-default table-responsive">
        <div class="panel-heading">
            Meeting Setup
					
            <span class="label label-info pull-right">@Model.MeetingDetailsMainModelList.Count() Items</span>
        </div>
        <div class="padding-md clearfix">
            <table class="table table-striped" id="dataTable">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>@Html.DisplayNameFor(model => model.MeetingTitle)</th>
                        <th>Meeting Date</th>
                        <th>Veneu</th>


                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.MeetingDetailsMainModelList.Any())
                    {
                        foreach (var item in Model.MeetingDetailsMainModelList)
                        {
                        <tr>
                            <td>@i</td>
                            <td>@item.MeetingTitle</td>
                            <td>@item.MeetingDate.ToShortDateString()</td>
                            <td>@item.Venue</td>

                            <td>
                                <a title="EmployeeDtls" class="fa fa-edit fa-lg" href="@Url.Action("AssingEmployee", "AddNewMeeting", new { id = item.MeetiingDetailsId })">Assign Employee</a> ||
                                <a title="Edit" class="fa fa-edit fa-lg" href="@Url.Action("Edit", "AddNewMeeting", new { id = item.MeetiingDetailsId })">Edit</a> ||
                                 <a title="View Employee" class="fa fa-edit fa-lg" href="@Url.Action("ViewAssignEmployee", "AddNewMeeting", new { id = item.MeetiingDetailsId })">View Employee</a> ||
                                 <a title="Delete" class="fa fa-minus-circle fa-lg" href="@Url.Action("DeleteMeeting", "AddNewMeeting", new { id = item.MeetiingDetailsId })" onclick="return confirm('Are you sure you wish to delete?');">Delete</a>


                            </td>
                        </tr>
                            i++;
                        }
                    }

                </tbody>
            </table>
        </div>
        <!-- /.padding-md -->
    </div>
    <!-- /panel -->
</div>
<!-- /.padding-md -->

<script>
    $(document).ready(function () {
        var success = @((TempData["SuccessMessage"] != null).ToString().ToLower());

        if (success == true) 
        {
            displayToastr();
        }

    });

    function displayToastr() {
        //alert('yes');
        // Display a info toast, with no title
        toastr.options = {

            "positionClass": "toast-top-center"
        }

        //toastr.options = {
        //    "closeButton": false,
        //    "debug": false,
        //    "newestOnTop": false,
        //    "progressBar": false,
        //    "positionClass": "toast-top-center",
        //    "preventDuplicates": false,
        //    "onclick": null,
        //    "showDuration": "300",
        //    "hideDuration": "1000",
        //    "timeOut": "5000",
        //    "extendedTimeOut": "1000",
        //    "showEasing": "swing",
        //    "hideEasing": "linear",
        //    "showMethod": "fadeIn",
        //    "hideMethod": "fadeOut"
        //}
        var Message = '@TempData["SuccessMessage"]';
        toastr.success(Message)

        //// Display a warning toast, with no title
        //toastr.warning('Softech Foundation, This the first warning for you!')

        //// Display a success toast, with a title
        //toastr.success('Softech Foudnation!', 'Congratulation for you, Mahedee!')

        //// Display an error toast, with a title
        //toastr.error('Softech Foundation', 'Please contact with system administrator.')
    };
</script>

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/AddNewMeeting/VUC_Add.cshtml
@model MobileAppAndroid.Models.MeetingDetailsMainModel

<div class="form-group">
    <label for="exampleInputEmail1">Meeting Title</label>
    @Html.TextBoxFor(model => model.MeetingTitle, new { @class = "form-control input-sm", @placeholder = "Enter Meeting Title", @required = "required" })
    @Html.ValidationMessageFor(model => model.MeetingTitle)

</div>

<div class="form-group col-md-6">
    <label for="exampleInputEmail1">Meeting Agenda</label>
    @Html.TextBoxFor(model => model.Agenda, new { @class = "form-control input-sm", @placeholder = "Enter Agenda", @required = "required" })
    @Html.ValidationMessageFor(model => model.Agenda)

</div>

<div class="form-group col-md-6">
    <label for="exampleInputEmail1">Meeting Venue</label>
    @Html.TextBoxFor(model => model.Venue, new { @class = "form-control input-sm", @placeholder = "Enter Venue", @required = "required" })
    @Html.ValidationMessageFor(model => model.Venue)

</div>

<div class="form-group col-md-6">
    <label for="exampleInputEmail1">Meeting Date</label>
    @Html.TextBoxFor(model => model.ObjReturnMeetingDetailsAdminViewModel.MeetingDate, new { @class = "datepicker form-control", @required = "required",@readonly="readonly" })
    @Html.ValidationMessageFor(model => model.MeetingDate)

</div>

<div class="form-group col-md-6 input-group bootstrap-timepicker">
    <label for="exampleInputEmail1">Meeting Time</label>
    @Html.TextBoxFor(model => model.MeetiingDetailsIdStr, new { @class = "form-control", @readonly = "readonly", @id = "Meetingtime" })
    @Html.ValidationMessageFor(model => model.MeetiingDetailsIdStr)

</div>

@*  <div class="input-group bootstrap-timepicker timepicker">
            <input id="timepicker2" type="text" class="form-control input-small">
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-time"></i>
            </span>
        </div>*@

<script type="text/javascript">
    $('#Meetingtime').timepicker({
        minuteStep: 1,
        template: 'dropdown',
        showSeconds: true,
        showMeridian: false,
        defaultTime: 'current'
    });

    $('.datepicker').datepicker({
        format: 'yyyy/mm/dd',
        "setDate": new Date(),
        "autoclose": true

    });
</script>

<div class="clearfix"></div>
@*<div class="form-group">
    <label class="col-lg-2 control-label">Date Picker</label>
    <div class="col-lg-10">
        <div class="input-group">
            <input type="text" value="06/10/2013" class="datepicker form-control">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
        </div>
    </div>
    <!-- /.col -->
</div>*@
<!-- /form-group -->
@*<div class="form-group">
    <label class="col-lg-2 control-label">Time Picker</label>
    <div class="col-lg-10">
        <div class="input-group bootstrap-timepicker">
            <input class="timepicker form-control" type="text" />
            <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
        </div>
    </div>
    <!-- /.col -->
</div>*@
<!-- /form-group -->

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/AddNewMeeting/ViewAssignEmployee.cshtml
@model MobileAppAndroid.Models.MeetingDetailsMainModel

@{
    ViewBag.Title = "ViewAssignEmployee";
    Layout = "~/Areas/AdminNew/Views/Shared/_Layout.cshtml";
    int i = 1;
}




<script src="~/Scripts/toastr.min.js"></script>
<link href="~/Content/toastr.min.css" rel="stylesheet" />

<div id="dialog-alert" style="display: none">
    <p>
        @TempData["msg"]!
    </p>
</div>

<div id="dialog-confirm" style="display: none">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        Are you sure to delete?
    </p>
</div>

<div id="dialog-edit" style="display: none">
</div>
<div id="dialog-detail" style="display: none">
</div>


<div class="padding-md">
    <div class="panel panel-default table-responsive">
        <div class="panel-heading">
            Assign Employee Details
					
            <span class="label label-info pull-right">@Model.MeetingEmployeeDetailsForAdminVMList.Count() Employee</span>
        </div>
        <div class="padding-md clearfix">
            <table class="table table-striped" id="dataTable">
                <thead>
                    <tr>
                        <th>SN</th>                       
                        <th>Employee Name</th>
                        <th>Remarks</th>
                        <th>FeedBack</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.MeetingEmployeeDetailsForAdminVMList.Any())
                    {
                        foreach (var item in Model.MeetingEmployeeDetailsForAdminVMList)
                        {
                        <tr>
                            <td>@i</td>
                            <td>@item.EmployeeName</td>
                            <td>@item.Remarks</td>
                            <td>@item.FeedBack</td>


                        </tr>
                            i++;
                        }
                    }

                </tbody>
            </table>
        </div>
        <!-- /.padding-md -->
    </div>
    <!-- /panel -->
</div>
<!-- /.padding-md -->

<script>
    $(document).ready(function () {
        var success = @((TempData["SuccessMessage"] != null).ToString().ToLower());

        if (success == true) 
        {
            displayToastr();
        }

    });

    function displayToastr() {
        //alert('yes');
        // Display a info toast, with no title
        toastr.options = {

            "positionClass": "toast-top-center"
        }

        //toastr.options = {
        //    "closeButton": false,
        //    "debug": false,
        //    "newestOnTop": false,
        //    "progressBar": false,
        //    "positionClass": "toast-top-center",
        //    "preventDuplicates": false,
        //    "onclick": null,
        //    "showDuration": "300",
        //    "hideDuration": "1000",
        //    "timeOut": "5000",
        //    "extendedTimeOut": "1000",
        //    "showEasing": "swing",
        //    "hideEasing": "linear",
        //    "showMethod": "fadeIn",
        //    "hideMethod": "fadeOut"
        //}
        var Message = '@TempData["SuccessMessage"]';
        toastr.success(Message)

        //// Display a warning toast, with no title
        //toastr.warning('Softech Foundation, This the first warning for you!')

        //// Display a success toast, with a title
        //toastr.success('Softech Foudnation!', 'Congratulation for you, Mahedee!')

        //// Display an error toast, with a title
        //toastr.error('Softech Foundation', 'Please contact with system administrator.')
    };
</script>