BitMeeting/MobileAppAndroid/MobileAppAndroid/Controllers/DepartmentMainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileAppAndroid.Models;
using MobileAppAndroid.Providers;
using System.Net.Http;
using System.Net;

namespace MobileAppAndroid.Controllers
{
    public class DepartmentMainController : Controller
    {
        //
        // GET: /DepartmentMain/

        public ActionResult Index()
        {
            DepartmentDetailsModel model = new DepartmentDetailsModel();
            DepartmentDetailsProviders pro = new DepartmentDetailsProviders();
            model.DepartmentDetailsModelList = pro.GetDepartmentList();
            return View(model);
        }

        public JsonResult Delete(string id)
        {
            DepartmentDetailsModel model = new DepartmentDetailsModel();
            model.DepartmentId = Convert.ToInt32(id);
            DepartmentDetailsProviders pro = new DepartmentDetailsProviders();
            var Message = new List<object>();

            if (pro.DeleteGroup(model.DepartmentId))
            {

                Message.Add(new { Success = "1", Message = "Successfully Deleted" });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }

            else
            {
                Message.Add(new { Success = "0", Message = "Error Please Try Again." });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }

        }



        public ActionResult Movies()
        {
            var movies = new List<object>();

            movies.Add(new { Title = "Ghostbusters", Genre = "Comedy", Year = 1984 });


            return Json(movies, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetMP()
        {
            DepartmentDetailsModel model = new DepartmentDetailsModel();
            DepartmentDetailsProviders pro = new DepartmentDetailsProviders();
            model.DepartmentDetailsModelList = pro.GetDepartmentList();
            return Json(model.DepartmentDetailsModelList, JsonRequestBehavior.AllowGet);

        }
    }
}

BitMeeting/MobileAppAndroid/MobileAppAndroid/Controllers/EmployeeMainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileAppAndroid.Models;
using MobileAppAndroid.Providers;

namespace MobileAppAndroid.Controllers
{
    public class EmployeeMainController : Controller
    {
        //
        // GET: /EmployeeMain/

        EmployeeRecordsProviders pro = new EmployeeRecordsProviders();
        public ActionResult Index()
        {
            EmployeeDetailsModel model = new EmployeeDetailsModel();
            model.EmployeeDetailsModelList = pro.GetList();
            return View(model);
        }


        public ActionResult EditEmployee(string EmpId, string Name, string Email, string Password, string UserType, string OrganizationID, string DepartmentId)
        {
            EmployeeDetailsModel model = new EmployeeDetailsModel();
            EmployeeRecordsProviders pro = new EmployeeRecordsProviders();
            model.Name = Name;
            model.UserPassword = Password;
            model.Email = Email;
            model.OrganizationId = Convert.ToInt32(OrganizationID);
            model.DepartmentId = Convert.ToInt32(DepartmentId);
            model.UserType = Convert.ToInt32(UserType);

            //Check Is alredy same email or not


            var Message = new List<object>();

            if (pro.EditEmployee(model))
            {

                Message.Add(new { Success = "1", Message = "Successfully Edited" });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }

            else
            {
                Message.Add(new { Success = "0", Message = "Error Please Try Again." });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }


        }

        public ActionResult EditEmployeeName(string EmpId, string Name)
        {
            EmployeeDetailsModel model = new EmployeeDetailsModel();
            EmployeeRecordsProviders pro = new EmployeeRecordsProviders();
            model.Name = Name;
            model.EmployeeId = Convert.ToInt32(EmpId);

            //Check Is alredy same email or not

            var Message = new List<object>();

            if (pro.EditEmployeeName(model))
            {

                Message.Add(new { Success = "1", Message = "Successfully Edited" });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }

            else
            {
                Message.Add(new { Success = "0", Message = "Error Please Try Again." });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }


        }

        public JsonResult GetEmployeeForEditMeeting(string MeetingId)
        {
            int MeetingIdInt = Convert.ToInt32(MeetingId);
            //get OrganizationID from meeting id

            MeetingDetailsProviders pro1 = new MeetingDetailsProviders();
            int OrganizationId = pro1.GetOrganizationIdFromMeetingId(MeetingIdInt);
            List<EmployeeDetailsForMeetingEditViewModel> List = new List<EmployeeDetailsForMeetingEditViewModel>();
            if (OrganizationId > 0)
            {
                var EmployeeDetails = pro.GetList().Where(x => x.OrganizationId == OrganizationId);
                foreach (var item in EmployeeDetails)
                {
                    var Obj = new EmployeeDetailsForMeetingEditViewModel()
                    {

                        EmployeeName = item.Name,
                        CheckedStatus = Utilities.GetCheckedStatus(item.EmployeeId, MeetingIdInt),
                        EmployeeId = item.EmployeeId.ToString(),
                        MeetingId = MeetingId

                    };
                    List.Add(Obj);

                }
                return Json(List, JsonRequestBehavior.AllowGet);

            }
            else
            {
                var Message = new List<object>();
                Message.Add(new { Success = "0", Message = "Error Please Try Again." });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }

        }


        public JsonResult DeleteEmployee(string EmployeeId)
        {
            EmployeeDetailsModel model = new EmployeeDetailsModel();
            model.EmployeeId = Convert.ToInt32(EmployeeId);
            //First delete employee from Meeting
            var Message = new List<object>();
            if (pro.DeleteEmployee(model.EmployeeId))
            {

                Message.Add(new { Success = "1", Message = "Delete Successfully." });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Message.Add(new { Success = "0", Message = "Error Please Try Again." });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }
        }




    }
}

BitMeeting/MobileAppAndroid/MobileAppAndroid/Controllers/MeetingDetailsMainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileAppAndroid.Models;
using MobileAppAndroid.Providers;
using System.Globalization;
using ImageResizer;
using System.IO;

namespace MobileAppAndroid.Controllers
{
    public class MeetingDetailsMainController : Controller
    {

        // GET: /MeetingDetailsMain/
        MeetingDetailsProviders pro = new MeetingDetailsProviders();
        public ActionResult Index()
        {

            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            model.MeetingDetailsMainModelList = pro.GetMeetingList();
            return View(model);
        }



        public ActionResult Create()
        {
            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            return View(model);
        }


        [HttpPost]
        public ActionResult Create(MeetingDetailsMainModel model)
        {
            pro.InsertMeetingDetails(model);
            return RedirectToAction("Index");
        }


        public JsonResult CreateMeeting(string MeetingTitle, string Venue, string Agenda, string CreatedBy, string MeetingDate, string MeetingTime, string OrganizationId)
        {

            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            model.MeetingTitle = MeetingTitle;
            model.Venue = Venue;
            model.Agenda = Agenda;
            model.CreatedBy = Convert.ToInt32(CreatedBy);
            DateTime NewDt = Convert.ToDateTime(MeetingDate);
            model.MeetingDate = NewDt;
            //Check Date
            DateTime TodayDate = DateTime.Now;
            var Message = new List<object>();
            if (NewDt >= TodayDate)
            {

                model.MeetingTime = TimeSpan.Parse(MeetingTime);
                model.OrganizationId = Convert.ToInt32(OrganizationId);

                int MeetingId = pro.InsertMeetingDetails(model);
                string MeetingIdstr = @"" + MeetingId + "";
                if (MeetingId > 0)
                {
                    //Get all employee List

                    Message.Add(new { Success = "1", MeetingId = MeetingIdstr, Message = "Successfully Inserted" });
                    return Json(Message, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    Message.Add(new { Success = "0", MeetingId = "0", Message = "Error Please Try Again." });
                    return Json(Message, JsonRequestBehavior.AllowGet);
                }
            }

            else
            {
                Message.Add(new { Success = "0", MeetingId = "0", Message = "Date not valid." });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }

        }

        public JsonResult EditMeetingCreateMeeting(string MeetingId, string MeetingTitle, string Venue, string Agenda, string CreatedBy, string MeetingDate, string MeetingTime, string OrganizationId)
        {
            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            model.MeetingTitle = MeetingTitle;
            model.Venue = Venue;
            model.Agenda = Agenda;
            model.MeetiingDetailsId = Convert.ToInt32(MeetingId);
            model.CreatedBy = Convert.ToInt32(CreatedBy);
            DateTime NewDt = Convert.ToDateTime(MeetingDate);
            model.MeetingDate = NewDt;
            //Check Date
            DateTime TodayDate = DateTime.Now;
            var Message = new List<object>();

            if (NewDt >= TodayDate)
            {
                model.MeetingTime = TimeSpan.Parse(MeetingTime);
                model.OrganizationId = Convert.ToInt32(OrganizationId);

                if (pro.EditMeetingDetails(model))
                {
                    string MeetingIdstrForVal = @"" + MeetingId + "";
                    Message.Add(new { Success = "1", MeetingId = MeetingIdstrForVal, Message = "Successfully Edited" });
                    return Json(Message, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    string MeetingIdstrForVal = @"" + MeetingId + "";
                    Message.Add(new { Success = "0", MeetingId = "0", Message = "No changes made." });
                    return Json(Message, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                Message.Add(new { Success = "0", MeetingId = "0", Message = "Date not valid." });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult DeleteMeeting(string MeetingId)
        {
            var Message = new List<object>();

            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            model.ObjMeetingEmployeeDetailsViewModel.MeetingId = Convert.ToInt32(MeetingId);

            if (pro.DeleteMeetingDetails(model.ObjMeetingEmployeeDetailsViewModel))
            {
                Message.Add(new { Success = "1", Message = "Successfully Deleted" });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Message.Add(new { Success = "0", Message = "Please Try Again" });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }
        }




        public JsonResult MeetingEmployeeDetails(string MeetingId, [System.Web.Http.FromUri] string employeeId)
        {
            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            String[] EmployeeIds = employeeId.Split(',');
            model.ObjMeetingEmployeeDetailsViewModel.MeetingId = Convert.ToInt32(MeetingId);
            model.ObjMeetingEmployeeDetailsViewModel.Status = 1;
            model.ObjMeetingEmployeeDetailsViewModel.Remarks = "";
            model.ObjMeetingEmployeeDetailsViewModel.Feedback = "";

            var Message = new List<object>();

            if (pro.InsertEmployeeInMeeting(model, EmployeeIds))
            {
                //Send Notification.........................................
                pro.SendNotificationToUser(model.ObjMeetingEmployeeDetailsViewModel.MeetingId);
                Message.Add(new { Success = "1", Message = "Successfully Inserted" });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Message.Add(new { Success = "0", Message = "Error Please Try Again" });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }

        }




        public JsonResult MeetingEmpGroupDetails(string MeetingId, [System.Web.Http.FromUri] string GroupId)
        {
            MeetingDetailsMainModel model = new MeetingDetailsMainModel();
            String[] GroupIds = GroupId.Split(',');
            model.ObjMeetingEmployeeDetailsViewModel.MeetingId = Convert.ToInt32(MeetingId);
            model.ObjMeetingEmployeeDetailsViewModel.Status = 1;
            model.ObjMeetingEmployeeDetailsViewModel.Remarks = "";
            model.ObjMeetingEmployeeDetailsViewModel.Feedback = "";

            var Message = new List<object>();
            model.EmployeeFromGroupIdViewModelList = pro.GetEmployeeListFromGroupIds(GroupIds);
            if (pro.InsertEmployeeGroupInMeeting(model))
            {
                pro.SendNotificationToUser(model.ObjMeetingEmployeeDetailsViewModel.MeetingId);
                Message.Add(new { Success = "1", Message = "Successfully Inserted" });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }

            else
            {
                Message.Add(new { Success = "0", Message = "Error Please Try Again" });
                return Json(Message, JsonRequestBehavior.AllowGet);
            }

        }




        //List Meeting For Employee
        public JsonResult GetMeetingListForEmp(string OrganizationId, string EmployeeId)
        {

            int OrgId = Convert.ToInt32(OrganizationId);
            int EmpId = Convert.ToInt32(EmployeeId);
            EmployeeDetailsModel model = new EmployeeDetailsModel();

            model.EmployeeMeetingDetailViewModelList = pro.GetEmployeeMeetingDetails(OrgId, EmpId).ToList();
            var Message = new List<object>();
            List<ReturnEmployeeMeetingDetailViewModel> ReturnList = new List<ReturnEmployeeMeetingDetailViewModel>();

            if (model.EmployeeMeetingDetailViewModelList.Count > 0)
            {
                foreach (var item in model.EmployeeMeetingDetailViewModelList)
                {
                    string MeetingIdStr = @"" + item.MeetiingDetailsId + "";
                    string OrganizationIdStr = @"" + OrganizationId + "";
                    string YesNoStatusStr = @"" + item.Status + "";

                    string TimeSpanDate = string.Format("{0:00}:{1:00}", item.MeetingTime.Hours, item.MeetingTime.Minutes);

                    if (string.IsNullOrEmpty(item.Remarks))
                    {
                        item.Remarks = @"" + 0 + "";
                    }
                    if (string.IsNullOrEmpty(item.FeedBack))
                    {
                        item.FeedBack = @"" + 0 + "";
                    }

                    ReturnList.Add(new ReturnEmployeeMeetingDetailViewModel { MeetiingDetailsId = MeetingIdStr, MeetingTitle = item.MeetingTitle.Replace("\"", string.Empty), Agenda = item.Agenda.Replace("\"", string.Empty), Venue = item.Venue.Replace("\"", string.Empty), MeetingTime = TimeSpanDate, MeetingDate = item.MeetingDate.ToShortDateString(), OrganizationId = OrganizationIdStr, YesNoStatus = YesNoStatusStr, Remarks = item.Remarks.Replace("\"", string.Empty), FeedBack = item.FeedBack.Replace("\"", string.Empty) });
                }
                //Message.Add(new { Success = "0", Message = "Error Please Try Again" });
                return Json(ReturnList, JsonRequestBehavior.AllowGet);
            }

BitMeeting/MobileAppAndroid/MobileAppAndroid/Views/Shared/_BootstrapLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    @Styles.Render("~/Content/themes/base/css", "~/Content/css")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
    <link href="~/Content/bootstrap-responsive.min.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="~/Content/icons/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/icons/apple-touch-icon-57-precomposed.png">
</head>

<body>

    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="#">Project name</a>
                <div class="nav-collapse">
                    <ul class="nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>

    <div class="container">

        @RenderBody()

    </div>
    <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>

BitMeeting/MobileAppAndroid/MobileAppAndroid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Softech Foundation</title>
    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />


    <!-- Font Awesome -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet">

    <!-- Pace -->
    <link href="~/css/pace.css" rel="stylesheet">

    <!-- Chosen -->
    <link href="~/css/chosen/chosen.min.css" rel="stylesheet" />

    <!-- Datepicker -->
    <link href="~/css/datepicker.css" rel="stylesheet" />

    <!-- Timepicker -->
    <link href="~/css/bootstrap-timepicker.css" rel="stylesheet" />

    <!-- Slider -->
    <link href="~/css/slider.css" rel="stylesheet" />

    <!-- Tag input -->
    <link href="~/css/jquery.tagsinput.css" rel="stylesheet" />

    <!-- WYSIHTML5 -->
    <link href="~/css/bootstrap-wysihtml5.css" rel="stylesheet" />

    <!-- Dropzone -->
    <link href='~/css/dropzone/dropzone.css' rel="stylesheet" />

    <!-- Endless -->
    <link href="~/css/endless.min.css" rel="stylesheet">
    <link href="~/css/endless-skin.css" rel="stylesheet">
</head>
<body>


    @RenderBody()
    <hr />
    <div class="clearfix"></div>
   @* <footer>
        <p>&copy; @DateTime.Now.Year - Softech Foundation Private Limited</p>
    </footer>*@


    @RenderSection("scripts", required: false)






    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- Jquery -->
    <script src="~/js/jquery-1.10.2.min.js"></script>

    <!-- Bootstrap -->
    <script src="~/bootstrap/js/bootstrap.min.js"></script>

    <!-- Chosen -->
    <script src='~/js/chosen.jquery.min.js'></script>

    <!-- Mask-input -->
    <script src='~/js/jquery.maskedinput.min.js'></script>

    <!-- Datepicker -->
    <script src='~/js/bootstrap-datepicker.min.js'></script>

    <!-- Timepicker -->
    <script src='~/js/bootstrap-timepicker.min.js'></script>

    <!-- Slider -->
    <script src='~/js/bootstrap-slider.min.js'></script>

    <!-- Tag input -->
    <script src='~/js/jquery.tagsinput.min.js'></script>

    <!-- WYSIHTML5 -->
    <script src='~/js/wysihtml5-0.3.0.min.js'></script>
    <script src='~/js/uncompressed/bootstrap-wysihtml5.js'></script>

    <!-- Dropzone -->
    <script src='~/js/dropzone.min.js'></script>

    <!-- Modernizr -->
    <script src='~/js/modernizr.min.js'></script>

    <!-- Pace -->
    <script src='~/js/pace.min.js'></script>

    <!-- Popup Overlay -->
    <script src='~/js/jquery.popupoverlay.min.js'></script>

    <!-- Slimscroll -->
    <script src='~/js/jquery.slimscroll.min.js'></script>

    <!-- Cookie -->
    <script src='~/js/jquery.cookie.min.js'></script>

    <!-- Endless -->
    <script src="~/js/endless/endless_form.js"></script>
    <script src="~/js/endless/endless.js"></script>
    <script src='~/js/bootstrap-slider.min.js'></script>

    <!-- Tag input -->
    <script src='~/js/jquery.tagsinput.min.js'></script>

    <!-- WYSIHTML5 -->
    <script src='~/js/wysihtml5-0.3.0.min.js'></script>
    <script src='~/js/uncompressed/bootstrap-wysihtml5.js'></script>

    <!-- Dropzone -->
    <script src='~/js/dropzone.min.js'></script>

    <!-- Modernizr -->
    <script src='~/js/modernizr.min.js'></script>

    <!-- Pace -->
    <script src='~/js/pace.min.js'></script>

    <!-- Popup Overlay -->
    <script src='~/js/jquery.popupoverlay.min.js'></script>

    <!-- Slimscroll -->
    <script src='~/js/jquery.slimscroll.min.js'></script>

    <!-- Cookie -->
    <script src='~/js/jquery.cookie.min.js'></script>

    <!-- Endless -->
    <script src="~/js/endless/endless_form.js"></script>
    <script src="~/js/endless/endless.js"></script>





</body>
</html>

BitMeeting/MobileAppAndroid/MobileAppAndroid/Views/Shared/_Layout123.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/toastr")

    @* @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")*@
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <img src="~/Images/SoftechLogo.png" />
                @*<p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>*@
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Meeting", "Index", "MeetingDetailsMain")</li>
                        <li>@Html.ActionLink("Employee", "Index", "EmployeeMain")</li>
                        <li>@Html.ActionLink("Department", "Index", "DepartmentMain")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>