BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Controllers/SetupDepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileAppAndroid.Models;
using MobileAppAndroid.Providers;

namespace MobileAppAndroid.Areas.AdminNew.Controllers
{
    public class SetupDepartmentsController : Controller
    {
        //
        // GET: /Admin/SetupDepartments/
        DepartmentDetailsProviders pro = new DepartmentDetailsProviders();
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Index()
        {
            DepartmentDetailsModel model = new DepartmentDetailsModel();
            model.DepartmentDetailsModelList = pro.GetDepartmentList();
            return View(model);
        }

        public ActionResult Create()
        {
            DepartmentDetailsModel model = new DepartmentDetailsModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(DepartmentDetailsModel model)
        {
            if (pro.InsertDepartment(model))
            {
                TempData["SuccessMessage"] = "success";
            }
            else
            {
                TempData["SuccessMessage"] = "Failure";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            DepartmentDetailsModel model = new DepartmentDetailsModel();
            model = pro.GetDepartmentList().Where(x => x.DepartmentId == id).SingleOrDefault();
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(DepartmentDetailsModel model)
        {

            if (pro.EditDeaprtment(model))
            {
                TempData["SuccessMessage"] = "success";
            }
            else
            {
                TempData["SuccessMessage"] = "Failure";
            }

            return RedirectToAction("Index");
        }


    }


}

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/SetupDepartments/Create.cshtml
@model MobileAppAndroid.Models.DepartmentDetailsModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminNew/Views/Shared/_Layout.cshtml";
}

<div class="padding-md">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Create New Department</div>
            <div class="panel-body">
                @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = " " }))
                {
                    @Html.ValidationSummary(true)
                    @Html.Partial("VUC_Add");
                    <div class="divider"></div>
                        
                    <div class="text-right">
                        <input class="btn btn-success btn-sm" type="submit" value="Save" />
                        @Html.ActionLink("Back", "Index", "SetupDepartments",null, new {@class="btn btn-warning btn-sm"})
                       @* <a class="btn btn-warning btn-sm"><i class="fa fa-chevron-left"></i>Back</a>*@
                    </div>
            
   
                }
            </div>
        </div>

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/SetupDepartments/Edit.cshtml
@model MobileAppAndroid.Models.DepartmentDetailsModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminNew/Views/Shared/_Layout.cshtml";
}

<div class="padding-md">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Edit Department Description</div>
            <div class="panel-body">
                @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = " " }))
                {
                    @Html.HiddenFor(m => m.DepartmentId)
                    @Html.ValidationSummary(true)
                    @Html.Partial("VUC_Add");
                    <div class="divider"></div>
                        
                    <div class="text-right">
                        <input class="btn btn-success btn-sm" type="submit" value="Edit" />
                        @Html.ActionLink("Back", "Index", "SetupDepartments", null, new { @class = "btn btn-warning btn-sm" })
                    </div>
            
   
                }
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/SetupDepartments/Index.cshtml
@model MobileAppAndroid.Models.DepartmentDetailsModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminNew/Views/Shared/_Layout.cshtml"; int i = 1;
}
<script src="~/Scripts/toastr.min.js"></script>
<link href="~/Content/toastr.min.css" rel="stylesheet" />



<div id="dialog-confirm" style="display: none">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        Are you sure to delete?
    </p>
</div>

<div id="dialog-edit" style="display: none">
</div>
<div id="dialog-detail" style="display: none">
</div>


<div class="padding-md">
    <div class="divider text-right">
        @Html.ActionLink("Add New", "Create", null, new { @class = "btn btn-primary" })
    </div>


    <div class="panel panel-default table-responsive">
        <div class="panel-heading">
            Department Setup
					
            <span class="label label-info pull-right">1 Items</span>
        </div>
        <div class="padding-md clearfix">
            <table class="table table-striped" id="dataTable">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>


                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.DepartmentDetailsModelList.Any())
                    {
                        foreach (var item in Model.DepartmentDetailsModelList)
                        {
                        <tr>
                            <td>@i</td>
                            <td>@item.Name</td>

                            <td>

                                <a title="Edit" class="fa fa-edit fa-lg" href="@Url.Action("Edit", "SetupDepartments", new { id = item.DepartmentId })">Edit</a> ||
                                 <a title="Delete" class="fa fa-minus-circle fa-lg" href="@Url.Action("Delete", "SetupDepartments", new { id = item.DepartmentId })" onclick="return confirm('Are you sure you wish to delete?');">Delete</a>


                            </td>
                        </tr>
                            i++;
                        }
                    }

                </tbody>
            </table>
        </div>
        <!-- /.padding-md -->
    </div>
    <!-- /panel -->
</div>
<!-- /.padding-md -->

<script>
    $(document).ready(function () {
        var success = @((TempData["SuccessMessage"] != null).ToString().ToLower());
        if (success == true) 
        {

            displayToastr();
        }

    });

    function displayToastr() {
        //alert('yes');
        // Display a info toast, with no title
        toastr.options = {

            "positionClass": "toast-top-center"
        }

        //toastr.options = {
        //    "closeButton": false,
        //    "debug": false,
        //    "newestOnTop": false,
        //    "progressBar": false,
        //    "positionClass": "toast-top-center",
        //    "preventDuplicates": false,
        //    "onclick": null,
        //    "showDuration": "300",
        //    "hideDuration": "1000",
        //    "timeOut": "5000",
        //    "extendedTimeOut": "1000",
        //    "showEasing": "swing",
        //    "hideEasing": "linear",
        //    "showMethod": "fadeIn",
        //    "hideMethod": "fadeOut"
        //}

        toastr.info('Department save successfully.')

        //// Display a warning toast, with no title
        //toastr.warning('Softech Foundation, This the first warning for you!')

        //// Display a success toast, with a title
        //toastr.success('Softech Foudnation!', 'Congratulation for you, Mahedee!')

        //// Display an error toast, with a title
        //toastr.error('Softech Foundation', 'Please contact with system administrator.')
    };
</script>

BitMeeting/MobileAppAndroid/MobileAppAndroid/Areas/AdminNew/Views/SetupDepartments/VUC_Add.cshtml
@model MobileAppAndroid.Models.DepartmentDetailsModel

<div class="form-group">
    <label for="exampleInputEmail1">Department Name</label>
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control input-sm", @placeholder = "Enter Department Name", @required = "required" })
    @Html.ValidationMessageFor(model => model.Name)

</div>